jenkins:
  systemMessage: "Welcome to Jenkins"
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "user1"
          password: "password1"
        - id: "user2"
          password: "password2"
  
  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: user1
            permissions:
              - Overall/Read
        - user:
            name: admin
            permissions:
              - Overall/Administer
  clouds:
    - kubernetes:
        name: "minikube"
        skipTlsVerify: true
        namespace: "default"
        jenkinsUrl: "http://host.docker.internal:8080"
        templates:
        - name: "curl"
          label: "curl"
          containers:
            - name: "curl"
              image: curlimages/curl:7.70.0
              privileged: 'false'
              ttyEnabled: 'false'
              workingDir: /home/jenkins/agent
        
  slaveAgentPort: 50000
  
jobs:
  - script: >
        folder('user1-folder') {
            description('Folder for user1')
            displayName('User1 Folder')
            authorization {
                permission('hudson.model.Item.Read:user1')
                permission('hudson.model.Item.Build:user1')
                permission('hudson.model.Item.Create:user1')
                permission('hudson.model.Item.Delete:admin')
            }
        }
  - script: >
        folder('user2-folder') {
            description('Folder for user2')
            displayName('User2 Folder')
            authorization {
                permission('hudson.model.Item.Read:user2')
                permission('hudson.model.Item.Build:user2')
                permission('hudson.model.Item.Create:user2')
                permission('hudson.model.Item.Delete:admin')
            }
        }
  - script: >
        folder('user4-folder') {
            description('Folder for user2')
            displayName('User2 Folder')
            authorization {
                permission('hudson.model.Item.Read:user1')
                permission('hudson.model.Item.Build:user1')
                permission('hudson.model.Item.Create:user1')
                permission('hudson.model.Item.Delete:admin')
            }
        }
  - script: >
        folder('admin-folder') {
            description('Folder for admin')
            displayName('Admin Folder')
            authorization {
                permission('hudson.model.Item.Read:admin')
                permission('hudson.model.Item.Build:admin')
                permission('hudson.model.Item.Create:admin')
                permission('hudson.model.Item.Delete:admin')
            }
        }

appearance:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true
unclassified:
  thinBackup:
    backupAdditionalFiles: false
    backupAdditionalFilesRegex: "^.*\\.(txt)$"
    backupBuildArchive: false
    backupBuildResults: true
    backupBuildsToKeepOnly: false
    backupConfigHistory: false
    backupNextBuildNumber: false
    backupPath: "/Users/selma/thin-backup"
    backupPluginArchives: false
    backupUserContents: false
    cleanupDiff: false
    diffBackupSchedule: "0 12 * * 1-5"
    excludedFilesRegex: "^.*\\.(log)$"
    failFast: true
    forceQuietModeTimeout: 120
    fullBackupSchedule: "0 12 * * 1"
    moveOldBackupsToZipFile: false
    nrMaxStoredFull: -1
    waitForIdle: true